# Generated by Django 3.2.11 on 2022-01-26 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('crm', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=45)),
                ('street', models.CharField(max_length=45)),
                ('complement', models.CharField(blank=True, max_length=200)),
                ('number', models.IntegerField()),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('client_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
