# Generated by Django 3.1.1 on 2022-01-30 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20220130_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='crm',
            new_name='regional_council',
        ),
    ]
