# Generated by Django 3.1.1 on 2022-01-31 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20220130_2122'),
        ('doctor', '0003_auto_20220130_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='client_cpf',
        ),
        migrations.AddField(
            model_name='doctor',
            name='appointment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment'),
        ),
    ]
