# Generated by Django 3.1.1 on 2022-01-31 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20220130_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='appointment_id',
        ),
    ]
