# Generated by Django 3.1.1 on 2022-01-30 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('drugstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugstore',
            name='client_cpf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
