# Generated by Django 3.1.1 on 2022-01-31 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugstore_orders', '0003_auto_20220130_2122'),
        ('drugstore', '0002_auto_20220130_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugstore',
            name='client_cpf',
        ),
        migrations.AddField(
            model_name='drugstore',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drugstore_orders.drugstoreorder'),
        ),
    ]
