# Generated by Django 3.1.1 on 2022-01-31 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20220130_2122'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_crm',
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_cpf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='call',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
