# Generated by Django 3.1.1 on 2022-01-31 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_doctor_appointment_id'),
        ('appointment', '0002_auto_20220130_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_rc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
    ]
