# Generated by Django 3.1.1 on 2022-01-31 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_doctor_rc'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
