# Generated by Django 3.2.11 on 2022-01-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=45)),
                ('street', models.CharField(max_length=45)),
                ('complement', models.CharField(blank=True, max_length=200)),
                ('number', models.IntegerField(blank=True)),
                ('cep', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
