# Generated by Django 3.1.1 on 2022-01-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='complement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
