# Generated by Django 3.2.11 on 2022-01-26 03:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drugstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugstoreOrder',
            fields=[
                ('idOrder', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_prescription', models.CharField(max_length=45)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=45)),
                ('street', models.CharField(blank=True, max_length=45)),
                ('complement', models.CharField(blank=True, max_length=200)),
                ('number', models.IntegerField(blank=True)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('drugstore_cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugstore.drugstore')),
            ],
        ),
    ]
