# Generated by Django 3.2.11 on 2022-01-27 00:49

from django.db import migrations, models
import drugstore_orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstore_orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugstoreorder',
            name='link_prescription',
        ),
        migrations.AddField(
            model_name='drugstoreorder',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=drugstore_orders.models.upload_image_prescription),
        ),
    ]
