# Generated by Django 3.1.1 on 2022-01-31 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20220130_2122'),
        ('drugstore_orders', '0002_auto_20220126_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugstoreorder',
            name='drugstore_cnpj',
        ),
        migrations.AddField(
            model_name='drugstoreorder',
            name='client_cpf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
