# Generated by Django 3.1.1 on 2022-01-31 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugstore', '0004_remove_drugstore_order_id'),
        ('drugstore_orders', '0003_auto_20220130_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugstoreorder',
            name='drugstore_cnpj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drugstore.drugstore'),
        ),
    ]
